### ISSUE TITLE
Infografía_Realidad Aumentada

### ISSUE THREAD

**Issue by EMMANUELRHZ** [SistemasTecTlaxiaco/infografia-EMMANUELRHZ#1]
![155386194-e7fd7b38-74fe-4adb-be1f-9b9407a1d114](https://user-images.githubusercontent.com/79876660/155386883-33579d54-8894-4a12-8a60-33cdd8298f71.jpg)

**Comment by EMMANUELRHZ** [comment]
![Infografía_RA](https://user-images.githubusercontent.com/61800187/155386194-e7fd7b38-74fe-4adb-be1f-9b9407a1d114.jpg)

**Comment by Brendalp** [comment]
Calificación=20

**Comment by josealfredo79** [comment]
Bien hecho...solo aplicar mejor diseño
